baseURL = "https://bernat.tech"
title = "Tech articles by Bernát Gábor"
languageCode = "en"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
ignoreLogs = ["warning-goldmark-raw-html"]

pagination.pagerSize = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[params]
author = "Bernát Gábor"
description = "Bernát Gábor's personal website"
keywords = "blog,developer,personal,python,packaging"
info = [
    "Bloomberg",
    "Python open-source",
    "software engineer",
]
avatarurl = "img/avatar.jpg"
dateFormat = "2006-01-01"
colorScheme = "auto"
hidecolorschemetoggle = false
customCSS = [
    "css/custom.css",
    "css/syntax.css",
]
favicon_16 = "img/android-chrome-192x192.png"
favicon_32 = "img/android-chrome-192x192.png"
touchIcon = "img/android-chrome-192x192.png"

[params.cloudflare]
token = "3ead932f454449a799915b1721c18874"

[[params.social]]
icon = "fa fa-github fa-2x"
name = "GitHub"
url = "https://github.com/gaborbernat/"
weight = 1

[[params.social]]
icon = "fa fa-heart fa-2x"
name = "GitHub Sponsor"
url = "https://github.com/sponsors/gaborbernat"
weight = 2

[[params.social]]
icon = "fa fa-twitter fa-2x"
name = "Twitter"
url = "https://twitter.com/gjbernat/"
weight = 3

[[params.social]]
icon = "fa-brands fa-bluesky fa-2x"
name = "Bluesky"
url = "https://bsky.app/profile/gjbernat.bsky.social"
weight = 4

[[params.social]]
icon = "fa-brands fa-mastodon fa-2x"
name = "Mastodon"
url = "https://fosstodon.org/@gaborbernat"
weight = 5

[[params.social]]
icon = "fa-brands fa-python fa-2x"
name = "PyPI"
url = "https://pypi.org/user/gaborbernat/"
weight = 6

[[params.social]]
icon = "fa fa-linkedin fa-2x"
name = "Linkedin"
url = "https://www.linkedin.com/in/gaborbernat/"
weight = 7

[[params.social]]
icon = "fa fa-envelope fa-2x"
name = "Google Mail"
url = "mailto:gaborjbernat@gmail.com"
weight = 8

[[params.social]]
icon = "fa fa-twitch fa-2x"
name = "Twitch"
url = "https://www.twitch.tv/gaborbernat"
weight = 9

[[params.social]]
icon = "fa fa-instagram fa-2x"
name = "Instagram"
url = "https://instagram.com/gabor_bernat"
weight = 10

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[[menu.main]]
name = "Blog"
url = "posts"
weight = 1

[[menu.main]]
name = "About"
url = "about"
weight = 2

[[menu.main]]
name = "Presentations"
url = "presentations"
weight = 3

[[menu.main]]
name = "Tags"
url = "tags"
weight = 4

[related]
includeNewer = true
threshold = 80
toLower = false
[[related.indices]]
name = "tags"
weight = 100
[[related.indices]]
name = "date"
weight = 10

[outputs]
home = ["HTML", "RSS", "JSON"]

[languages.en]
languageName = ":uk:"

[markup.goldmark.renderer]
unsafe = false

[markup.highlight]
anchorLineNos = true
codeFences = true
guessSyntax = false
lineAnchors = "c"
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = false
style = "monokai"
tabWidth = 4

[markup.tableOfContents]
endLevel = 3
ordered = true
startLevel = 2

[caches.getresource]
maxAge = "30m"

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[module]
[[module.imports]]
path = "github.com/luizdepra/hugo-coder"
