baseURL = "https://bernat.tech"
title = "Tech articles by Bernát Gábor"
theme = "congo"
languageCode = "en"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
ignoreLogs = ["warning-goldmark-raw-html"]

[params]
description = "Bernát Gábor's personal website"
mainSections = ["posts"]
showAuthor = true
showDate = true
showReadingTime = true
showWordCount = false

[params.author]
name = "Bernát Gábor"
image = "img/avatar.jpg"
headline = "Bloomberg | Python open-source | software engineer"
bio = "Software engineer passionate about Python packaging and open-source development."
links = [
  { github = "https://github.com/gaborbernat/" },
  { twitter = "https://twitter.com/gjbernat/" },
  { mastodon = "https://fosstodon.org/@gaborbernat" },
  { linkedin = "https://www.linkedin.com/in/gaborbernat/" },
  { email = "mailto:gaborjbernat@gmail.com" },
]

[params.homepage]
layout = "profile"
showRecent = true

[params.article]
showDate = true
showDateUpdated = true
showAuthor = true
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showWordCount = false
showComments = false

[params.list]
showTableOfContents = false
groupByYear = true

[params.footer]
showCopyright = true
showThemeAttribution = true

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[[menu.main]]
name = "Blog"
pageRef = "posts"
weight = 1

[[menu.main]]
name = "About"
pageRef = "about"
weight = 2

[[menu.main]]
name = "Presentations"
pageRef = "presentations"
weight = 3

[languages.en]
languageName = "English"
weight = 1

[markup.goldmark.renderer]
unsafe = false

[markup.highlight]
anchorLineNos = true
codeFences = true
guessSyntax = false
lineAnchors = "c"
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = false
style = "monokai"
tabWidth = 4

[markup.tableOfContents]
endLevel = 3
ordered = true
startLevel = 2

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5
